name: Update LeetCode Daily

on:
  schedule:
    - cron: "0 0 * * *" # 每天 UTC 时间 00:00 运行
  workflow_dispatch: # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:  # 添加权限声明
      contents: write  # 允许工作流写入仓库
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true  # 必须开启凭证持久化
          fetch-depth: 0            # 避免 shallow clone 导致推送问题
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Run script
        run: |
          pip install requests
          python ./.github/scripts/update_readme.py

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update LeetCode daily problem"
          git push
